AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  kimelt:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: kimelt
      Handler: main.lambda_handler
      Runtime: python3.8
      CodeUri: ./app
      Timeout: 10
      Events:
        zeitplanEquipoEliminar:
          Type: Api
          Properties:
            Path: /equipos/{equipo_id}
            Method: delete
        zeitplanEquipoObtener:
          Type: Api
          Properties:
            Path: /equipos/{equipo_id}
            Method: get
        zeitplanEquipoAgregar:
          Type: Api
          Properties:
            Path: /equipos
            Method: post
        zeitplanUsuarioEliminar:
          Type: Api
          Properties:
            Path: /v1/usuario/{usuario_id}
            Method: delete
        zeitplanUsuarioObtener:
          Type: Api
          Properties:
            Path: /v1/usuario/{usuario_id}
            Method: get
        zeitplanUsuarioAgregar:
          Type: Api
          Properties:
            Path: /v1/usuario/
            Method: post
      Layers:
        - !Ref kimeltLayer
  kimeltLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: ./layer.zip
