name: Deploy to Lambda

on:
  push:
    branches:
      - main  # Ejecutar este flujo de trabajo en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_LAMBDA_ALIAS: produccion  # Establece el valor de AWS_LAMBDA_ALIAS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      region: ${{ secrets.region }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $region

      - name: Publish Lambda Version
        run: aws lambda publish-version --function-name kimelt

      - name: Set AWS Lambda Alias
        run: echo "AWS_LAMBDA_ALIAS=$AWS_LAMBDA_ALIAS" >> $GITHUB_ENV

      - name: Run Deployment Script
        run: |
          chmod +x deploy.sh  # Asegúrate de que el script sea ejecutable
          ./deploy.sh  # Ejecuta el script de implementación
